### ISSUE TITLE
First contact create date (field empty)- should default the creator of the company information 

### ISSUE THREAD

**Issue by alexandreabou** [jamesmillerburgess/customer-management#24]
Inside the companies 

- What is the field section – first contact create date ? (should it not default the creator of this company ?)  The field is currently empty 

![capture](https://user-images.githubusercontent.com/32377726/30998135-07df3ef2-a4ff-11e7-9943-9f5786c91edc.JPG)

**Comment by jamesmillerburgess** [comment]
Eventually there will be a way to create contacts and associate them with companies. Once that is in place this field would show you when you have done so.

I put the column in here because that is what HubSpot has as a column, but I'm not sure why they felt it is so important as to have it as a default. Maybe this would be better replaced with something else like 'Last Interaction' or 'Total Pipeline Amount'? Need to think from the perspective of a sales user on this one.

In the meantime, I will remove the column in the next release.
