### ISSUE TITLE
Opportunities worflow can't view next milestones 

### ISSUE THREAD

**Issue by alexandreabou** [jamesmillerburgess/customer-management#32]
1. When changing the opportunity from Quality to buy to Presentation Scheduled we can't preview the full name of the next steps 

![test](https://user-images.githubusercontent.com/32377726/31165405-47461382-a8eb-11e7-98cc-a6af4bd49604.JPG)

**Comment by jamesmillerburgess** [comment]
This is a browser-specific issue with IE11. I'm working on it and it has already taken some 6 hours of my time! I have been waiting until I fix this issue before sending out release notes, because my definition of 'done' includes that everything works on IE11.

If you take a look in Chrome, you can see how it is supposed to look.

**Comment by alexandreabou** [comment]
thanks for the update I understand now why it is displayed this way.

**Comment by jamesmillerburgess** [comment]
Should be fixed in the current version.
